spring:
  config:
    import: 'consul:'
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
        prefix: config
        format: YAML
        fail-fast: true
server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: '*'