spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: depoimento
      username: root
      password: root
      authentication-database: admin
      auto-index-creation: true